# Generated by Django 4.0.3 on 2022-04-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='drive_unit',
            field=models.CharField(choices=[('Rear', 'Rear'), ('Front', 'Front')], max_length=200),
        ),
    ]
